# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupdetail',
            table='group_detail',
        ),
    ]
