# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo03', '0002_auto_20181115_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdetail',
            old_name='info_id',
            new_name='info',
        ),
    ]
