# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo03', '0003_auto_20181115_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
