# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo03', '0005_auto_20181115_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='demo03.User'),
        ),
    ]
